### ISSUE TITLE
build fail on Linux

### ISSUE THREAD

**Issue by davephillips** [JTriggerFish/TriggerFish-VCV#1]
Fedora 23 Linux
Rack 0.6.2b (from source)
GCC 5.3.1

Greetings ! I'm looking forward to trying out your modules but I'm hitting a build error here:

g++ -Isrc -Isrc/dsp -Isrc/models -Wsuggest-override -std=c++11 -std=c++17 -mavx  -DSLUG=TriggerFish-Elements -fPIC -I../../include -I../../dep/include -DVERSION=0.6.1 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN -c -o build/src/TfVCA.cpp.o src/TfVCA.cpp
In file included from src/TfVCA.cpp:4:0:
src/dsp/filters.hpp: In constructor ‘dsp::GaussianFilter<width, order, T>::GaussianFilter()’:
src/dsp/filters.hpp:199:33: error: expected ‘,’ before ‘)’ token
         static_assert(order >= 1);
                                 ^
src/dsp/filters.hpp:199:33: error: expected string-literal before ‘)’ token
src/dsp/filters.hpp:200:33: error: expected ‘,’ before ‘)’ token
         static_assert(width >= 1);
                                 ^
src/dsp/filters.hpp:200:33: error: expected string-literal before ‘)’ token
../../compile.mk:64: recipe for target 'build/src/TfVCA.cpp.o' failed
make: *** [build/src/TfVCA.cpp.o] Error 1

Any suggestions for a fix ? TIA!

**Comment by JTriggerFish** [comment]
Thanks for trying it out ! I had tested the build on windows and mac but not linux.
I have deleted this piece of code that was not used, would you mind trying again ?

**Comment by davephillips** [comment]
Done ! Thanks for the quick response, your plugin builds cleanly and all modules instantiate without problems, except for this:

[31.602 warn src/window.cpp:697] Failed to load SVG ./plugins/TriggerFish-VCV/res/TfVDPO.svg

That occurs because the file in your repo is named TfVdpo.svg and UNIX/Linux is case-sensitive. I copied the file to TfVDPO.svg and it's all good now. A screenshot from Rack in Fedora 23:

![triggerfishes](https://user-images.githubusercontent.com/7815938/45596997-36788800-b993-11e8-881b-0ba47e9ceb62.png)

**Comment by JTriggerFish** [comment]
Thanks for the heads up ! renamed now.
