### ISSUE TITLE
Stereo Inputs

### ISSUE THREAD

**Issue by blackearth2014** [JTriggerFish/TriggerFish-VCV#5]
Can you add stereo inputs to the VCA and Filter?

Thanks

**Comment by JTriggerFish** [comment]
Hmm thanks for the suggestion. I think the proper idiomatic way in VCV rack would be to instantiate two modules of each.
Of course it makes it a bit annoying to tweak the parameters for both but some modules like Vult knob can help with that.
It would be good if there was a way to link knobs in VCV rack. 
I will suggest it on the main repo.
If that doesn’t go anywhere I’ll implement stereo versions.

**Comment by blackearth2014** [comment]
Cool Breeze

**Comment by JTriggerFish** [comment]
Closing this as multichannel patch cables seem to be on the vcv roadmap.

**Comment by blackearth2014** [comment]
Cool Breeze!
