### ISSUE TITLE
Output and bleed in VCA not working

### ISSUE THREAD

**Issue by the1andonlydrno** [JTriggerFish/TriggerFish-VCV#6]
Hi, I'm just about to finish episode 13 of "what does this knob do?" and this time it's about VCAs. It seems, that at your VCA the output knob and therefore the bleed knob have no function or is ist so subtle that I do not hear it and also the scope doesn't show it?

**Comment by JTriggerFish** [comment]
Hello,

Glad to hear that you're trying out the modules.
They should both definitely be working. Output controls the overall output level of the VCA, and will add gentle warmth / saturation as you push it.
You can see it on a scope by having a sine wave as input and patching a high constant value to the linear CV input ( such that the sound is always 'on' ) and then playing with the output level, you should see the output getting closer to a square wave.

The CV bleed is more subtle, it adds a bit of the CV input to the output. Best way to hear it is to have no input sound but to patch in a very fast envelope to one of the CV inputs, and to set the CV and bleed level to max.
You will hear a small click on the output when the envelope triggers. This is something that happens on analogue VCAs and when in small doses, makes then sound more snappy.

**Comment by the1andonlydrno** [comment]
thanks for the fast response, bleed is indeed very subtle and I hear and see it now, but output still does nothing, I tried the trick with a fixed CV before and even with a really high resolution there is nothing, the sine stays a sine and won't change

**Comment by JTriggerFish** [comment]
Hmm you are right, just tested and it indeed has no effect, something went wrong here, apologies ! 
Will fix ASAP.

**Comment by JTriggerFish** [comment]
Fixed. Thank you so much for raising the issue ! 
It's annoying to think that people might have tried the module and written it off due to me breaking this in the previous version.

I've notified the community builders so hopefully this should be updated in the plugin manager in the coming days.
I can also provide you with a binary build directly ( just let me know your platform ) so you can have it quicker if you like.

**Comment by the1andonlydrno** [comment]
no problem, I always ask if I do not understand things or find something missing and I learned to build the binaries, just downloading the zip file, thanks for fixing it so fast

**Comment by JTriggerFish** [comment]
Cool, let me know how you get on.
By the way it's easier to see the effect of gain and output level on a frequency analyser like the one from Bogaudio. You can see harmonics being added to a sine wave.

**Comment by the1andonlydrno** [comment]
works perfectly, thanks again

**Comment by glocke01** [comment]
![image](https://user-images.githubusercontent.com/12255580/74475205-f9107680-4e74-11ea-8188-713334b4f45a.png)

AFAICT, bleed isn't doing anything. I'm using low audio frequency AM here, so there ought to be something. The screencap here shows 1:1 on the scope, but using a frequency analyzer shows similar results.

**Comment by glocke01** [comment]
Nevermind! i can see a small effect on the analyzer. Issue remains closed.
