### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by gilbertohasnofb** [JTriggerFish/TriggerFish-VCV#7]
Your plugin is not compatible any longer with the current version of VCV Rack. Are you planning on updating it and releasing a new version?

**Comment by JTriggerFish** [comment]
Hello,

The api changes require a fair bit of work, I might try and get to it next month but I’m not sure there are enough users to warrant it.

**Comment by gilbertohasnofb** [comment]
Hi there, thanks for taking a look at this. If you do get around doing it, that would be great, but I completely understand your point about perhaps not having enough users to justify the work. I was hoping that the API changes were small and that upgrading it to 1.x would require just very small changes.

**Comment by diimdeep** [comment]
Slop was featured in this video https://youtu.be/2c5eHWcC4kk?t=449 really cool module. 👍 Please update to v1 ;)
